### DISCUSSION TITLE
How to use monospace font in websites like GitHub?

### DISCUSSION THREAD

**Discussion by k4leg** [qutebrowser/qutebrowser#7368] [Q&A] [answered]
If I set `content.user_stylesheets` to `/home/k4leg/.config/qutebrowser/stylesheet.css`, then everything will be monospace except code. But I want other way round: code will be monospace, other doesn't change. So `font-family` doesn’t work, I need something else, but what?

`stylesheet.css` content:

```css
* {
        font-family: 'JetBrains Mono', monospace;
}
```
