### DISCUSSION TITLE
Font-related slowness after update to Qt6

### DISCUSSION THREAD

**Discussion by Aster89** [qutebrowser/qutebrowser#7862] [Q&A]
Since I updated qutebrowser last time (to Qt6) I find that when I type keys after `:open [-t]` , the reaction of the filtering is extremely slow, eventaully the browser visually freezes for several seconds, and it must eat so much RAM, because I hear the vent spinning more loudly.

With the help of #7850, I manged to attribute this performance regression to some of my settings. Specifically, these (which I honestly don't even remember why I put there; proabaly I wanted to show emojis somwhere, who knows :smile:)
```python
# in $HOME/.config/qutebrowser/config.py
# ...
c.fonts.default_family = ['DejaVuSansMono Nerd Font Mono', 'xos4 Terminus', 'Terminus']
# ...
```
```yml
# in $HOME/.config/qutebrowser/autoconfig.yml
  # ...
  fonts.default_family:
    global:
    - DejaVuSansMono Nerd Font Mono
    - xos4 Terminus
    - Terminus
  # ...
```
If I comment out those lines, everything seems to be better (probably as far as before, even if I don't really feel like that, probably because my perception has been altered by the frustrating slowness I've observed in the last few days).

Is this behavior normal? If not, why am I observing it?
