### DISCUSSION TITLE
Low frame rate when a video on youtube is fullscreened

### DISCUSSION THREAD

**Discussion by groggone** [qutebrowser/qutebrowser#8165] [Q&A]
I don't know what's causing this but the video lags or have low frame rate when it is fullscreened. It works just fine and doesn't do the same thing when qutebrowser is launched through: `qutebrowser --temp-basedir`

Here is my autoconfig.yml:
```
# If a config.py file exists, this file is ignored unless it's explicitly loaded
# via config.load_autoconfig(). For more information, see:
# https://github.com/qutebrowser/qutebrowser/blob/main/doc/help/configuring.asciidoc#loading-autoconfigyml
# DO NOT edit this file by hand, qutebrowser will overwrite it.
# Instead, create a config.py - see :help for details.

config_version: 2
settings:
  auto_save.session:
    global: true
  colors.webpage.darkmode.enabled:
    global: true
  colors.webpage.darkmode.policy.images:
    global: smart-simple
  colors.webpage.darkmode.policy.page:
    global: always
  colors.webpage.preferred_color_scheme:
    global: dark
  content.desktop_capture:
    global: true
  content.media.audio_capture:
    https://app.zoom.us: true
    https://discord.com: true
    https://meet.google.com: true
    https://www.messenger.com: true
  content.media.audio_video_capture:
    https://meet.google.com: true
  content.media.video_capture:
    https://app.zoom.us: true
    https://meet.google.com: true
  content.notifications.enabled:
    https://app.zoom.us: false
    https://meet.google.com: true
    https://uploadhaven.com: false
    https://www.bennish.net: true
    https://www.facebook.com: false
    https://www.reddit.com: true
    https://www.youtube.com: true
  content.register_protocol_handler:
    https://mail.google.com?extsrc=mailto&url=%25s: true
  downloads.location.directory:
    global: /home/lines/
  downloads.location.prompt:
    global: true
  downloads.location.remember:
    global: true
  downloads.position:
    global: bottom
  fileselect.handler:
    global: default
  qt.args:
    global:
    - ignore-gpu-blacklist
    - enable-accelerated-2d-canvas
    - enable-gpu-memory-buffer-video-frames
    - enable-gpu-rasterization
    - enable-native-gpu-memory-buffers
    - enable-oop-rasterization
    - enable-zero-copy
    - enable-features=WebRTCPipeWireCapturer
    - enable-features=WaylandWindowDecorations
  qt.chromium.process_model:
    global: process-per-site-instance
  qt.force_software_rendering:
    global: qt-quick
  qt.workarounds.disable_accelerated_2d_canvas:
    global: always
  session.lazy_restore:
    global: true
  url.default_page:
    global: https://www.google.com/
  url.searchengines:
    global:
      DEFAULT: https://www.google.com/search?hl=en&q={}
  url.start_pages:
    global: https://www.google.com
```

Here is my config.py:
```
config.load_autoconfig()

c.fonts.default_family = "terminus"
c.qt.args += [
    "ignore-gpu-blacklist",
    "enable-accelerated-2d-canvas",
    "enable-gpu-memory-buffer-video-frames",
    "enable-gpu-rasterization",
    "enable-native-gpu-memory-buffers",
    "enable-oop-rasterization",
    "enable-zero-copy",
]

config.bind('yf', 'hint links yank')
config.bind('yF', 'hint links yank-primary')

config.bind('Sb', 'bookmark-list')
config.bind('Sh', 'history')
config.bind('Sk', 'open qute://bindings')
config.bind('Ss', 'set')
config.bind('SB', 'bookmark-list -t')
config.bind('SH', 'history -t')
config.bind('SK', 'open -t qute://bindings')
config.bind('SS', 'open -t qute://settings')

config.bind('<Ctrl+1>', 'tab-focus 1')
config.bind('<Ctrl+2>', 'tab-focus 2')
config.bind('<Ctrl+3>', 'tab-focus 3')
config.bind('<Ctrl+4>', 'tab-focus 4')
config.bind('<Ctrl+5>', 'tab-focus 5')
config.bind('<Ctrl+6>', 'tab-focus 6')
config.bind('<Ctrl+7>', 'tab-focus 7')
config.bind('<Ctrl+8>', 'tab-focus 8')
config.bind('<Ctrl+9>', 'tab-focus -1')

config.bind('<Ctrl+Shift+!>', 'tab-move 1')
config.bind('<Ctrl+Shift+@>', 'tab-move 2')
config.bind('<Ctrl+Shift+#>', 'tab-move 3')
config.bind('<Ctrl+Shift+$>', 'tab-move 4')
config.bind('<Ctrl+Shift+%>', 'tab-move 5')
config.bind('<Ctrl+Shift+^>', 'tab-move 6')
config.bind('<Ctrl+Shift+&>', 'tab-move 7')
config.bind('<Ctrl+Shift+*>', 'tab-move 8')
config.bind('<Ctrl+Shift+(>', 'tab-move -1')

# config.bind('<Alt+Shift+!>', 'tab-move 1')
# config.bind('<Alt+Shift+@>', 'tab-move 2')
# config.bind('<Alt+Shift+#>', 'tab-move 3')
# config.bind('<Alt+Shift+$>', 'tab-move 4')
# config.bind('<Alt+Shift+%>', 'tab-move 5')
# config.bind('<Alt+Shift+^>', 'tab-move 6')
# config.bind('<Alt+Shift+&>', 'tab-move 7')
# config.bind('<Alt+Shift+*>', 'tab-move 8')
# config.bind('<Alt+Shift+(>', 'tab-move -1')

config.bind('<Ctrl+PgDown>', 'tab-prev')
config.bind('<Ctrl+PgUp>', 'tab-next')
config.bind('<Ctrl+PgDown>', 'tab-prev')

config.bind('<Ctrl+Shift+PgUp>', 'tab-move +')
config.bind('<Ctrl+Shift+PgDown>', 'tab-move -')

config.bind('<Ctrl+Shift+r>', 'restart')
config.bind('<Ctrl+Shift+n>', 'open -p')
```
