### ISSUE TITLE
Remember zoom level

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#2869]
Most other browsers remember the zoom level (per page / site) that was previously used. It seems that qutebrowser doesn't, but I would like to have this feature.

**Comment by ianpan870102** [comment]
I would love that as well. Been looking for an answer

**Comment by jgkamat** [comment]
#3782 will provide one way to get this functionality.

**Comment by ianpan870102** [comment]
Dear Jay,

Cheers mate, I'll check that out.

Ian

2018-05-17 23:16 GMT+08:00 Jay Kamat <notifications@github.com>:

**Comment by amacfie** [comment]
If this is implemented it should be optional via a setting

**Comment by martin-braun** [comment]
On macOS it's even worse, because despite zoom settings being stored in the session yml, they aren't load.

One of my windows have this in my default session:

```yaml
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2025-03-14T03:34:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: WhatsApp
      url: https://web.whatsapp.com/
      zoom: 0.75
```

and I'm using:

```py
c.auto_save.session = True
c.session.default_name = "default"
```

Auto saving and loading works fine, but my zoom level snaps back to 100% whenever I relaunch. It's sadly a terrible experience.
