### ISSUE TITLE
Automate macOS/Windows releases via GitHub Actions

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3725]
It'd be nice to automatically push releases via ~~Travis/AppVeyor~~ GitHub Actions when a tag is pushed, at least for macOS and Windows. I've historically been uncomfortable with letting the cloud™ push releases - however:

- I currently don't have easy access to a Mac
- Mac releases need to be built on an old macOS version (#3722)
- Windows releases are painful and I probably won't have a valid Windows license in ~1.5 years anymore (not that it'd be a problem, but it's additional work :laughing:)
- Dependencies of qutebrowser are already released that way, so if there's some security issue on Travis/Appveyor, it probably doesn't make a difference either way...
- It'd greatly streamline the release process.
- Those releases currently aren't signed (and won't be), only the source release is. I can still easily do the source release locally.

**Comment by gulkily** [comment]
Will doing this also allow for koshering the app so that it can be run without admin rights?

**Comment by The-Compiler** [comment]
@gulkily That in itself won't change anything in how releases look. However, it shouldn't need admin rights to run. If it does, please open a separate issue with more information.

**Comment by The-Compiler** [comment]
Here's a rough draft:

```yaml
name: Upload release
on:
  tags:
    - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1.1.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ github.ref }}"
          release_name: "${{ github.ref }}"
          body: |
            Check the [changelog](https://github.com/qutebrowser/qutebrowser/blob/master/doc/changelog.asciidoc) for changes in this release.
    outputs:
      upload_url: "${{ steps.create-release.outputs.upload_url }}"

  upload-release:
    runs-on: "${{ matrix.os }}"
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
          - os: macos-10.15
          - os: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build release
        run: "python scripts/dev/build_release.py"
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: FIXME
          asset_name: FIXME
          asset_content_type: FIXME
```

One problem I only noticed now: GitHub Actions only supports macOS 10.15 Catalina, which would mean we wouldn't support older macOS versions. That's kind of a deal breaker, unfortunately...
