### ISSUE TITLE
Add settings for Chromium's dark mode

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5394]
Splitting this off from #2377 since a lot of comments are about that.

I just looked through some of the [Blink settings](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/settings.json5) - most of them don't work, but there's a group of "force dark mode" settings there which work (since Qt 5.14) and which I'd like to expose.

Relevant links:

- [Settings definitions](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/settings.json5?q=darkModeImagePolicy&sq=package:chromium&dr=C&l=876)
- [Related issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1002664)
- [Issue with some example configs](https://bugs.chromium.org/p/chromium/issues/detail?id=985961)

## darkMode

Qt 5.14 way of setting the dark mode algorithm. In the current Chromium, this is renamed to `darkModeInversionAlgorithm`.

- kOff = 0 (deprecated)
- kSimpleInvertForTesting = 1 (For testing only, does a simple 8-bit invert of every RGB pixel component)
- kInvertBrightness = 2
- kInvertLightness = 3
- kInvertLightnessLAB = 4 (default)

## darkModeEnabled

bool, instead of the above in the current Chromium version, so probably in Qt 5.15.

## darkModeGrayscale

bool, doesn't seem to have any effect (?)

default: false

## darkModeContrast

-1 to +1

default: 0

## darkModeClassifierType

- kIcon = 0
- kGeneric = 1 (default)

## darkModeImagePolicy

- kFilterAll = 0 (Apply dark-mode filter to all images.)
- kFilterNone = 1 (default: Never apply dark-mode filter to any images.)
- kFilterSmart = 2 (Apply dark-mode based on image content.)

## darkModePagePolicy

- kFilterAll = 0 (Apply dark-mode filter to all frames, regardless of content.)
- kFilterByBackground = 1 (default: Apply dark-mode filter to frames based on background color)

## darkModeTextBrightnessThreshold

```
// Text colors with brightness below this threshold will be inverted, and
// above it will be left as in the original, non-dark-mode page.  Set to 256
// to always invert text color or to 0 to never invert text color.
```

default: 150

## darkModeBackgroundBrightnessThreshold

```
// Background elements with brightness above this threshold will be inverted,
// and below it will be left as in the original, non-dark-mode page.  Set to
// 256 to never invert the color or to 0 to always invert it.
//
// Warning: This behavior is the opposite of text_brightness_threshold!
```

default: 205

## darkModeImageGrayscale

default: 0.0

---

I'll need to think how to expose all this to qutebrowser - but you can already use those settings by adding something like `blink-settings=darkMode=4,darkModeImagePolicy=0` to `qt.args`.

**Comment by The-Compiler** [comment]
# Changes in Qt 5.14.2

By @rien333:

> @The-Compiler ever since Qt 5.14.2 (I think? maybe you have an idea), the setting `blink-settings=darkMode=4` now interferes with what I think is the color defined by `c.colors.webpage.bg`. This can produce some pretty funky looking results, where previously there was just white text on a black  background. Most prominently, this happens on plain html pages (e.g. [github raw thingies](https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/install.asciidoc)). Any idea if there is anything that can be done against this? 
> 
> One thing that works against the plain html color thing is setting `c.colors.webpage.bg` to white. But this will also have the undesired effect that any (uncached?) page that loads will briefly produce a white flash, sort of nullifying the purpose of having everything load in black. (at this point, I'll probably just choose a color whose's LAB inversion gives a nice tradeoff between non-white flashes and readability on plain-ish html).
> 
> EDIT:
> Maybe I need to fiddle around with `darkModeBackgroundBrightnessThreshold` now to make everything play nice together?

Probably this bugfix:

[Fix applying background color on RenderView (Ida198fb0) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/292932)

For this bug:

[[QTBUG-81781] QWebEnginePage setBackgroundColor broken sometime after Qt 5.12.6 - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-81781)

So according to that, setBackgroundColor didn't work at all before 5.14.2.

However, there are some more related changes to Qt 5.15, maybe they'll change that behavior again in some way:

- [Use SetBaseBackgroundColorOverride for setting background color (If4c1e228) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/296225)
- [Stop sending ViewMsg_SetBackgroundOpaque to renderer (I02bed3f0) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/296227)

**Comment by The-Compiler** [comment]
# Changes in Qt 5.15

With Qt 5.15, I can't get the above commandline to work anymore. I think Chromium changed something internally (as I can't get those flags to work with Chromium anymore either...). Did anyone find out yet what the correct flags to pass are there? I'm a bit confused by the code so far...

**Comment by rien333** [comment]
> Probably this bugfix:
 [Fix applying background color on RenderView (Ida198fb0) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/292932)

I'm almost totally sure that that bugfix caused the behavior I was describing, Since then I've reverted that specific commit, and that indeed restored the old behavior.

**Comment by yousufinternet** [comment]
> # Changes in Qt 5.15
> ~With Qt 5.15, I can't get the above commandline to work anymore.~ I think Chromium changed something internally (as I can't get those flags to work with Chromium anymore either...). Did anyone find out yet what the correct flags to pass are there? I'm a bit confused by the code so far...
> 
> * [about_flags.cc: Flag definition](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/about_flags.cc;l=2904-2913;drc=db99e6f42c71d92834f555e8c310be616ec581b6?originalUrl=https:%2F%2Fcs.chromium.org%2F)
> * [about_flags.cc: Flag variations](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/about_flags.cc;l=427-479;drc=c19c486772e381c3b8534adcadf8bd336c251d7e?originalUrl=https:%2F%2Fcs.chromium.org%2F)
> * [settings.json5](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/settings.json5;l=882-942;drc=43bbd38f475b9d9663f1ffabf2fef9fb26466af4?originalUrl=https:%2F%2Fcs.chromium.org%2F)
> * [Possibly relevant change](https://source.chromium.org/chromium/chromium/src/+/8f6ed96495d04270fe46ba8b861d291fd1a4dcea?originalUrl=https%2F:%2F%2F%2Fcs.chromium.org%2F)
> 
> Based on that I'd expect this to work, but it doesn't seem to...:
> 
> ```
> blink-settings=forceDarkModeInversionAlgorithm=4,forceDarkModeEnabled=true
> ```
> 
> edit: Ah, that change above was _after_ the Chromium snapshot in the 5.15 release - this seems to work:
> 
> ```
> blink-settings=darkModeEnabled=true,darkModeInversionAlgorithm=4
> ```

How exactly can I use this in qutebrowser?

is the following correct? because I am not getting any dark websites 
qutebrowser --qt-arg darkModeEnabled true --qt-arg darkModeInversionAlgorithm 4

**Comment by The-Compiler** [comment]
@yousufinternet Either use the `qt.args` setting like outlined in the original post, or use `--qt-flag blink-settings=darkModeEnabled=true,darkModeInversionAlgorithm=4`

**Comment by yousufinternet** [comment]
This is really cool, I have been waiting for this for a long time.
Thanks for helping me out!

**Comment by The-Compiler** [comment]
Here's a first draft for a `configdata.yml` addition:

```yaml
## dark mode

# darkModeClassifierType is not exposed, as the icon classifier isn't actually implemented in Chromium:
# https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/graphics/dark_mode_icon_classifier.cc

colors.webpage.darkmode.enabled:
  default: false
  type: Bool
  desc: "Automatically render all web contents using a dark theme."
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.algorithm:
  default: lightness-cielab
  desc: "Algorithm for modifying how colors are rendered with darkmode."
  type:
    name: String
    valid_values:
      # kInvertLightnessLAB
      - lightness-cielab: Modify colors by converting them to CIE L*a*b color
            space and inverting the L value.
      # kInvertLightness
      - lightness-hsl: Modify colors by converting them to the HSL color space
            and inverting the lightness (i.e. the "L" in HSL).
      # kInvertBrightness
      - brightness-rgb: Modify colors by subtracting each of r, g, and b from
            their maximum value.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.contrast:
  default: 0
  type:
    name: Float
    minval: -1
    maxval: 1
  desc: >-
    Contrast for dark mode.

    This only has an effect when the algorithm is set to `lightness-hsl` or
    `brightness-rgb`.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.policy.images:
  default: never
  type:
    name: String
    valid_values:
      - always: Apply dark mode filter to all images.
      - never: Never apply dark mode filter to any images.
      - smart: Apply dark mode based on image content.
  desc: Which images to apply dark mode to.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.policy.page:
  default: smart
  type:
    name: String
    valid_values:
      - always: Apply dark mode filter to all frames, regardless of content.
      - smart: Apply dark mode filter to frames based on background color.
  desc: Which pages to apply dark mode to.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.treshold.text:
  default: 205
  type:
    name: Int
    minval: 0
    maxval: 256
  desc: >-
      Threshold for inverting text with dark mode.

      Text colors with brightness below this threshold will be inverted, and
      above it will be left as in the original, non-dark-mode page.  Set to 256
      to always invert text color or to 0 to never invert text color.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.treshold.background:
  default: 0
  type:
    name: Int
    minval: 0
    maxval: 256
  desc: >-
      Threshold for inverting background elements with dark mode.

      Background elements with brightness above this threshold will be inverted,
      and below it will be left as in the original, non-dark-mode page.  Set to
      256 to never invert the color or to 0 to always invert it.

      Note: This behavior is the opposite of `treshold.text`!
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.grayscale.all:
  default: false
  type: Bool
  desc: >-
    Render all colors as grayscale.

    This only has an effect when the algorithm is set to `lightness-hsl` or
    `brightness-rgb`.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false

colors.webpage.darkmode.grayscale.images:
  default: 0
  type:
    name: Float
    minval: 0
    maxval: 1
  desc: >-
    Desurate images in dark mode.

    If set to 0, images are left as-is. If set to 1, images are completely
    grayscale. Values between 0 and 1 desaturate the colors accordingly.
  restart: true
  backend:
    QtWebEngine: Qt 5.14
    QtWebKit: false
```

Does that seem like an accurate and understandable explanation of those values, and is everything consistent there?

also cc @mschilli87 :wink:
