### ISSUE TITLE
Handling of credentials embedded in URLs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5410]
Looks like there's a long consensus (to some degree) between browser vendors to ignore credentials which are parts of URLs:

- https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3
- https://www.chromestatus.com/feature/5669008342777856
- https://www.ietf.org/rfc/rfc3986.html#section-3.2.1

We probably already get the underlying Chromium changes (Chromium 59, so Qt 5.10), but I wonder if there's anything left for qutebrowser to do there.

**Comment by Kingdread** [comment]
It looks like at least the saved session can contain user/password combinations:

```
windows:
- [...]
  tabs:
  - active: true
    history:
    - active: true
      [...]
      url: https://foo:bar@kingdread.de/
```

Maybe worth stripping them there too, for the sake of security and since Chromium probably will start rejecting them at some point anyway then.
