### ISSUE TITLE
Segmentation Fault writing email at gmail.com

### ISSUE THREAD

**Issue by gmagno** [qutebrowser/qutebrowser#6183]
**Version info**:

```
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: no
jinja2: 2.11.3
pygments: no
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021
```

**Does the bug happen if you start with `--temp-basedir`?**:
No.

**Description**
The browser crashed while writing an email in gmail. And now, every time I start qutebrowser, it shows me the "Whoops!" crash report window, unresponsively, and crashes again.

**How to reproduce**

Not sure, this was the first time it crashed while using gmail. But now every time I open the browser, it crashes. I would probably have to share the entire list of pages I was visiting at the time.

Here's several attempts at opening the browser:

```
$ qutebrowser
[33876:33891:0219/134235.255737:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
fish: “qutebrowser” terminated by signal SIGSEGV (Address boundary error)

$ qutebrowser
[34611:34622:0219/134435.697168:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
fish: “qutebrowser” terminated by signal SIGSEGV (Address boundary error)

$ qutebrowser
[35088:35106:0219/134443.528388:ERROR:simple_index_file_posix.cc(61)] Could not get file info for /home/gm/.cache/qutebrowser/webengine/Cache/todelete_91a322b3014eae37_0_1
[35088:35106:0219/134443.529552:ERROR:simple_index_file_posix.cc(61)] Could not get file info for /home/gm/.cache/qutebrowser/webengine/Cache/todelete_a1b836d610108599_0_1
[35088:35106:0219/134443.532179:ERROR:simple_index_file_posix.cc(61)] Could not get file info for /home/gm/.cache/qutebrowser/webengine/Cache/todelete_9907eb6f7efaaef9_0_1
[35088:35103:0219/134446.896055:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[35088:35103:0219/134446.944526:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
fish: “qutebrowser” terminated by signal SIGSEGV (Address boundary error)

$ qutebrowser
[35571:35586:0219/134458.010872:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[35571:35586:0219/134458.013315:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
fish: “qutebrowser” terminated by signal SIGSEGV (Address boundary error)

$ qutebrowser
[36057:36072:0219/134512.331136:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[36057:36072:0219/134512.335257:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
fish: “qutebrowser” terminated by signal SIGSEGV (Address boundary error)
```

And the frozen crash report window a couple of seconds before it crashes again:

![image](https://user-images.githubusercontent.com/46817915/108535884-8d988a80-72ba-11eb-95d9-6b79414063ca.png)

**Comment by The-Compiler** [comment]
FWIW this is unlikely to be an issue in qutebrowser itself.

I assume if you run with `--temp-basedir` and visit GMail, it doesn't happen then? What OS/distribution is this on?

As for your existing browsing session, you should be able to edit `~/.local/share/qutebrowser/sessions/_autosave.yml` to remove the culprit - make sure you take a backup before that though, so that we can perhaps continue to track this down.

**Comment by gmagno** [comment]
> FWIW this is unlikely to be an issue in qutebrowser itself.
I imagined this could be related to one of qutebrowser dependencies, but I had to report it here anyways.

> I assume if you run with --temp-basedir and visit GMail, it doesn't happen then?
That's correct.

> What OS/distribution is this on?
```
$ neofetch
                   -`                    gm@gm-ultra
                  .o+`                   -----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: Inspiron 7560
               `+oooooo:                 Kernel: 5.10.17-hardened1-1-hardened
               -+oooooo+:                Uptime: 3 hours, 51 mins
             `/:-:++oooo+:               Packages: 1140 (pacman)
            `/++++/+++++++:              Shell: bash 5.1.4
           `/++++++++++++++:             Resolution: 1920x1080
          `/+++ooooooooooooo/`           WM: i3
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       CPU: Intel i7-7500U (4) @ 2.000GHz
     /ossssssss/        +ssssooo/-       GPU: NVIDIA GeForce 940MX
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel HD Graphics 620
  `+sso+:-`                 `.-/+oso:    Memory: 2472MiB / 15811MiB
 `++:.                           `-/+/
 .`                                 `/

```

> you should be able to edit ~/.local/share/qutebrowser/sessions/_autosave.yml
Thanks that was useful.

> remove the culprit - make sure you take a backup before that though, so that we can perhaps continue to track this down
Yup, removing all the "Gmail" titled history entries did the trick.

**Comment by gmagno** [comment]
Okay, I managed to make it crash with the following `_autosave.yml`:

```
windows:
  - active: true
    geometry: !!binary |
      AdnQywADAAAAAAAAAAAAAAAAB38AAAQaAAAAAAAAAAAAAAd/AAAEGgAAAAAAAAAAB4AAAAAAAAAA
      AAAAB38AAAQa
    tabs:
      - history:
          - active: true
            last_visited: "2021-02-19T10:30:01"
            pinned: false
            scroll-pos:
              x: 0
              y: 0
            title: cheatsheet-big.png (3342×2060)
            url: qute://help/img/cheatsheet-big.png
            zoom: 1.25
      - active: true
        history:
          - active: true
            last_visited: "2021-02-19T12:21:38"
            pinned: false
            scroll-pos:
              x: 0
              y: 0
            title: Gmail
            url: https://gmail.com
            zoom: 1.25
```

If I replace `url: https://gmail.com` with `url: https://google.com` it won't crash anymore.
Does this help?
