### ISSUE TITLE
qutebrowser crashes when trying to open link in new tab

### ISSUE THREAD

**Issue by dedifferentiator** [qutebrowser/qutebrowser#6324]
**Version info**:

``` yaml
qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.3
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.35.2
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 2.1 Mesa 20.3.4
Platform: Linux-5.11.8-zen1-1-zen-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/dorrt/.cache/qutebrowser
config: /home/dorrt/.config/qutebrowser
data: /home/dorrt/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/dorrt/.config/qutebrowser/config.py has been loaded
Uptime: 0:07:46
```
**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

When I try to open some links in new tab with `Ctrl+LButton` on [lichess.org](lichess.org), qutebrowser crashes with 
`[1]    12071 trace trap (core dumped)  qutebrowser`

**How to reproduce**
1. Open https://lichess.org/zk44wv1m
2. Hover the cursor over the `DrNykterstein`'s profile link (picture attached) and try to open his profile in new tab with `Ctrl+LButton` 
    
![image](https://user-images.githubusercontent.com/32426842/112369639-1739de80-8ce5-11eb-93ac-834d442818f8.png)
