### ISSUE TITLE
can not start in v2.5.0, Win11 and Python 3.10.4

### ISSUE THREAD

**Issue by test210820** [qutebrowser/qutebrowser#7099]
![屏幕截图 2022-04-03 181618](https://user-images.githubusercontent.com/65008815/161422796-62fe7551-c2a7-42ae-ac4a-7198d7e40eba.png)

**Comment by test210820** [comment]
## autoconfig.yml

```yml
config_version: 2
settings:
  bindings.commands:
    global:
      normal:
        J: tab-prev
        K: tab-next
        d: null
        dd: tab-close
        j: scroll-px 0 100
        k: scroll-px 0 -100
  colors.webpage.darkmode.enabled:
    global: false
  content.autoplay:
    global: false
  content.media.audio_capture:
    https://www.youtube.com: false
  content.proxy:
    global: socks://127.0.0.1:55555
  scrolling.smooth:
    global: true
  tabs.show:
    global: switching
  zoom.default:
    global: '150'
```
