### ISSUE TITLE
Simplify settings structure

### ISSUE THREAD

**Issue by atchim** [qutebrowser/qutebrowser#7592]
Recently I've been trying to split my configurations for qutebrowser to achieve more organization. My ideia was to have a `c.toml` file containing settings that could be set via the `c` variable used in `config.py` in addition to the usual `config.py` file, where I would keep settings configured via the `config` variable. This idea is quite similar to the one proposed in the bottom section of the configuring page (qute://help/configuring.html), which uses YAML instead.

For instance, by implementing this, I would be able to have the following configuration in the `c.toml` file.

```toml
[tabs]
new_position.unrelated = 'next'
padding = {bottom = 0, left = 0, right = 0, top = 0}
position = 'left'
select_on_remove = 'last-used'
show = 'switching'
title.format = '{audio}{index} {current_title}'
width = 50
```

To read and set the settings gathered from the `c.toml` file, I tried the approach suggest by the previously mentioned page with some adaptations, as the following snippet shows.

```python
# Contents of `config.py`

import tomli

from typing import Any, TYPE_CHECKING
if TYPE_CHECKING: config = Any

def dict_attrs(obj, path=''):
  if isinstance(obj, dict):
    for k, v in obj.items():
      yield from dict_attrs(v, '{}.{}'.format(path, k) if path else k)
  else:
    yield path, obj

with open(config.configdir / 'c.toml', 'rb') as f:
  data = tomli.load(f)

for k, v in dict_attrs(data):
  config.set(k, v)
```

The problem with the previous implementation is that it would set `tabs.padding.bottom` (and also top, left and right) to `0`, but `tabs.padding.bottom` and similar variations for other directions are not valid settings because currently the `tabs.padding` settings takes a `dict` as value.

My proposal is to allow the user to specify settings  that takes `dict` as value in a "flattened" way. I.e., instead of doing `:set tabs.padding {'bottom': 0, ...}`, the user would be able to do `:set tabs.padding.bottom 0`.

**Comment by toofar** [comment]
I'm having a little trouble following the problem description when it is mixed in with a proposal. Are you saying that [this example](https://qutebrowser.org/doc/help/configuring.html#_reading_a_nested_yaml_file) doesn't work in all cases (like `tabs.padding`)?

**Comment by atchim** [comment]
@toofar, yes, the example does not work when the settings requires a `dict` as value. In fact, the configuration guide mentions about this issue. But the point of this feature request is the implementation of a feature to allows the user to set settings that require a `dict` as value, in a simplified fashion. This way, the user would be allowed to run `:set tabs.padding.bottom 0` for example.

Is it clear to you now? I'm sorry for my lack of clarity in the explanation.

**Comment by The-Compiler** [comment]
I'm against this as a "magic syntax" for `:set`, because it's impossible to do this in a generalized way so that using the same syntax works in a `config.py` too (if `c.tabs.padding` is a dict, `c.tabs.padding.bottom` will be an `AttributeError`, and we can't change anything about that).

We do already have the `:config-dict-*` commands to manipulate dicts, and `:config-dict-add --replace tabs.padding bottom 0` will already do exactly this.

Not sure what to do to make this more discoverable - any ideas on that front, @atchim? Maybe a `:config-dict-set` command, even if that's just an alias for `:config-dict-add --replace` (though it could check that the key already *does* exist, I suppose).

I've also been thinking about renaming `:set` to `:config-set`, but I think I got some pushback on that.

**Comment by atchim** [comment]
For my specific case, I did not mentioned here before but I figured out some workaround to be able to split my `c` configurations into a TOML file.

That is my `config.py` file now:

```python
from typing import TYPE_CHECKING, Any

import tomli

if TYPE_CHECKING:
  config = Any

config.load_autoconfig(False)
config.source('bindings.py')

def dict_attrs(obj, path=''):
  if isinstance(obj, dict):
    for k, v in obj.items():
      # WORKAROUND: For settings that requires a `dict` as value.
      if (
        path == 'tabs' and k == 'padding'
        or path == 'url' and k == 'searchengines'
      ):
        yield f'{path}.{k}', v
      else:
        yield from dict_attrs(v, f'{path}.{k}' if path else k)
  else:
    yield path, obj

def set_c():
  with open(config.configdir / 'c.toml', 'rb') as f:
    data = tomli.load(f)

  palette = data['colors'].pop('_palette')

  for k, v in dict_attrs(data):
    if k.startswith('colors.'):
      v = [palette[i] for i in v] if isinstance(v, list) else palette[v]
    config.set(k, v)

set_c()
```

And that is my `c.toml` file:

<details>
  <summary><code>c.toml</code></summary>

  ```toml
  auto_save.session = true
  completion.shrink = true
  fonts.default_family = 'Hack Nerd Font'
  keyhint.radius = 0
  prompt.radius = 0
  spellcheck.languages = ['en-US', 'pt-BR']
  statusbar.show = 'in-mode'

  [colors]
  _palette = [
    '#080808',
    '#0c0c0c',
    '#121212',
    '#1a1a1a',
    '#252525',
    '#383838',
    '#5a5a5a',
    '#959595',
    '#ff5b5b',
    '#bc8f05',
    '#54a900',
    '#00ad2b',
    '#00a7a7',
    '#6b90ff',
    '#ba74ff',
    '#fc4ad0',
  ]

  [colors.completion]
  category.bg = 1
  category.fg = 7
  category.border.bottom = 1
  category.border.top = 1
  even.bg = 0
  fg = [7, 6, 10]
  item.selected.bg = 2
  item.selected.border.bottom = 2
  item.selected.border.top = 2
  item.selected.fg = 7
  item.selected.match.fg = 10
  match.fg = 14
  odd.bg = 0
  scrollbar.bg = 0
  scrollbar.fg = 4

  [colors.contextmenu]
  disabled.bg = 0
  disabled.fg = 6
  menu.bg = 0
  menu.fg = 7
  selected.bg = 1
  selected.fg = 7

  [colors.downloads]
  bar.bg = 0
  start.fg = 0
  start.bg = 10
  stop.fg = 0
  stop.bg = 11
  error.fg = 0
  error.bg = 8

  [colors.hints]
  bg = 14
  fg = 0
  match.fg = 6

  [colors.keyhint]
  bg = 0
  fg = 7
  suffix.fg = 10

  [colors.messages]
  error.bg = 8
  error.border = 8
  error.fg = 0
  info.bg = 11
  info.border = 11
  info.fg = 0
  warning.bg = 10
  warning.border = 10
  warning.fg = 0

  [colors.prompts]
  bg = 0
  border = 0
  fg = 7
  selected.bg = 1

  [colors.statusbar]
  caret.bg = 0
  caret.fg = 7
  caret.selection.bg = 0
  caret.selection.fg = 7
  command.bg = 0
  command.fg = 7
  command.private.bg = 0
  command.private.fg = 7
  insert.bg = 0
  insert.fg = 7
  normal.bg = 0
  normal.fg = 7
  passthrough.bg = 0
  passthrough.fg = 7
  private.bg = 0
  private.fg = 6
  progress.bg = 7
  url.error.fg = 8
  url.fg = 7
  url.hover.fg = 14
  url.success.http.fg = 7
  url.success.https.fg = 11
  url.warn.fg = 10

  [colors.tabs]
  bar.bg = 1
  even.bg = 0
  even.fg = 6
  indicator.error = 8
  indicator.start = 10
  indicator.stop = 11
  odd.bg = 0
  odd.fg = 6
  pinned.even.bg = 1
  pinned.even.fg = 6
  pinned.odd.bg = 1
  pinned.odd.fg = 6
  pinned.selected.even.bg = 0
  pinned.selected.even.fg = 7
  pinned.selected.odd.bg = 0
  pinned.selected.odd.fg = 7
  selected.even.bg = 0
  selected.even.fg = 7
  selected.odd.bg = 0
  selected.odd.fg = 7

  [downloads]
  location.directory = '~/Downloads'
  location.prompt = false
  location.suggestion = 'both'
  position = 'bottom'
  remove_finished = 0

  [hints]
  border = '0px solid'
  radius = 0

  [tabs]
  new_position.unrelated = 'next'
  padding = {bottom = 0, left = 0, right = 0, top = 0}
  position = 'left'
  select_on_remove = 'last-used'
  show = 'switching'
  title.format = '{audio}{index} {current_title}'
  width = 50

  [url]
  default_page = 'https://www.google.com'
  start_pages = 'https://www.google.com'

  [url.searchengines]
  DEFAULT = 'https://google.com/search?q={}'
  a = 'https://wiki.archlinux.org/index.php?search={}'
  d = 'https://duckduckgo.com/?q={}'
  dpl = 'https://www.deepl.com/translator#au/au/{}'
  g = 'https://www.google.com/search?q={}'
  gb = 'https://gentoobrowse.randomdan.homeip.net/search?criteria={}'
  gbp = 'https://gentoobrowse.randomdan.homeip.net/packages/{}'
  gh = 'https://github.com/search?q={}'
  'gh/' = 'https://github.com/{}'
  gt = 'https://translate.google.com/?sl=auto&text={}'
  mdn = 'https://developer.mozilla.org/en-US/search?q={}'
  rs = 'https://doc.rust-lang.org/std/index.html?search={}'
  rsc = 'https://docs.rs/releases/search?query={}'
  sc = 'https://soundcloud.com/search?q={}'
  w = 'https://wikipedia.org/w/index.php?search={}'
  y = 'https://www.youtube.com/results?search_query={}'
  zu = 'http://gpo.zugaina.org/Search?search={}'
  ```
</details>

Since my case is already solved and there is no way to "simplify" how to set `dict` values, I think that maybe it does not make sense  anymore to this issue be still open.

@The-Compiler, I think that the good usage of `:config-dict-add` may be mentioned in the guides related to configuration if it is not already. To be honest, I was not aware of such command until you mention about that here, although I am far from being a qutebrowser expert. About the alias to `:set`, honestly I think that I am not qualified to give an opinion about that.
