### ISSUE TITLE
qutebrowser adblock-update reports sock version 5 protocol error

### ISSUE THREAD

**Issue by csfreebird** [qutebrowser/qutebrowser#7641]
**Version info**:
```
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3

CPython: 3.10.6
PyQt: 5.15.6

sip: 6.5.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.14.0
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.2
QtNetwork SSL: OpenSSL 3.0.2 15 Mar 2022

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.2.5
Platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35, 64bit
Linux distribution: Ubuntu 22.04.2 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/dean/.cache/qutebrowser
config: /home/dean/.config/qutebrowser
data: /home/dean/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/dean/.config/qutebrowser/config.py has been loaded
Uptime: 4:07:38
```

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

run adblock-update, I get the message: reports sock version 5 protocol error
My qutebrowser is using localhost socks 5 proxy.

```
cat autoconfig.yml 
# If a config.py file exists, this file is ignored unless it's explicitly loaded
# via config.load_autoconfig(). For more information, see:
# https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#loading-autoconfigyml
# DO NOT edit this file by hand, qutebrowser will overwrite it.
# Instead, create a config.py - see :help for details.

config_version: 2
settings:
  colors.webpage.darkmode.enabled:
    global: true
  content.proxy:
    global: socks://localhost:8888
  window.hide_decoration:
    global: true

```

**How to reproduce**
