### ISSUE TITLE
CSS lack of support for :not()

### ISSUE THREAD

**Issue by victorbnl** [qutebrowser/qutebrowser#7673]
**Version info**:

qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.13, based on Chromium 87.0.4280.144
Qt: 5.15.9 (compiled 5.15.8)

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

When I go into my liked songs on Spotify, there is a lack of padding at the right of the song covers. Here is the relevant property:

```css
[dir="ltr"] .HcMOFLaukKJdK5LfdHh0 > :not(:last-child), [dir="ltr"] .bfQ2S9bMXr_kJjqEfcwA > :not(:last-child, .dZiDwJihz32GwQunXhnB), [dir="ltr"] .gvLrgQXBFVW6m9MscfFA > :not(:last-child)
{
    margin-right: 16px;
}
```

I’m pretty sure this is the relevant property because disabling it on Firefox makes it look exactly the same as qutebrowser. Now I don’t know what in this causes it not to work in qutebrowser but my best bet is it is the :not() that is not supported. Tell me if it’s not, I’ll rename the issue.

**How to reproduce**

Head over to open.spotify.com, log in and navigate to a playlist.

**Screenshot**

Firefox on the left, qutebrowser on the right.

![image](https://user-images.githubusercontent.com/39555268/233867876-43d2f1c9-a34b-4661-8dde-73bb579b5fa3.png)
