### ISSUE TITLE
Possibility to change tooltip color

### ISSUE THREAD

**Issue by gadefox** [qutebrowser/qutebrowser#7706]
.. in `qute://settings` or let's use colors for right click menu e.g. `colors.contextmenu.menu.fg and colors.contextmenu.menu.bg` values. Ta

**Comment by The-Compiler** [comment]
Also see #4520

**Comment by gadefox** [comment]
@The-Compiler, I changed 2 source files `mainwindow.py` and the `yaml` definition so I can set the color and the font of QT tooltip.
[x.tar.gz](https://github.com/qutebrowser/qutebrowser/files/11582033/x.tar.gz)

**Comment by gadefox** [comment]
```
        QToolTip {
            {% if conf.fonts.tooltip %}
                font: {{ conf.fonts.tooltip }};
            {% endif %}
            {% if conf.colors.tooltip.bg %}
                background: {{ conf.colors.tooltip.bg }};
            {% endif %}
            {% if conf.colors.tooltip.fg %}
                color: {{ conf.colors.tooltip.fg }};
            {% endif %}
            border: 0;
            padding: 2px;
        }
```

**Comment by gadefox** [comment]
changes in `/config/configdata.yml`:
```
colors.tooltip.bg:
  type:
    name: QssColor
    none_ok: true
  default: null
  desc: >-
    Background color of the tooltip.

    If set to null, the Qt default is used.

colors.tooltip.fg:
  type:
    name: QssColor
    none_ok: true
  default: null
  desc: >-
    Foreground color of the tooltip.

    If set to null, the Qt default is used.

colors.contextmenu.menu.bg:
...
```
