### ISSUE TITLE
Use dotted paths instead of section/option for config values.

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#893]
I think this was originally suggested by @Carpetsmoker but I'd like some more opinions on this.

What about using dotted option names instead of the current distinction between sections/options? Some examples:
- `:set general private-browsing true` -> `:set general.private-browsing true`
- `:set colors completion.item.selected.bg` -> `:set colors.completion.item.selected.bg`

Advantages:
- Probably makes some commands and code easier as it's only one argument instead of two.
- The completion for `:set` shows (and allows the user to filter) all options in all sections (though code could be added to do the same even with the current section/option scheme).

Disadvantages:
- Makes some code more complicated where it's interested in e.g. all config changes of a given section.
- The completion for `:set` might show too much, and it's not nicely grouped in categories.
- More config breakage

In YAML config files (which will be one way to write the config), those dotted elements could be handled as children:

``` yaml
- settings
  general:
    private-browsing: true
  colors:
    completion:
      fg: white
      bg: #333333
      category:
        fg: white
        bg: ...
        border:
          top: black
          bottom: black
      item:
        selected:
          bg: #e8c000
          fg: black
          border:
            top: #bbbb00
            bottom: #bbbb00
    statusbar:
      fg: white
      bg: black
      error:
        fg: white
        error: red
```

Note some options which have a value _and_ children will need to be renamed (e.g. `statusbar.fg.error` because `statusbar.fg` has a value as well).
